name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y sshpass jq curl

    - name: Call Open Weather API via RapidAPI
      env:
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      run: |
        API_URL="https://community-open-weather-map.p.rapidapi.com/weather?q=London,uk&units=metric"
        RESPONSE=$(curl -s -X GET "$API_URL" \
          -H "X-RapidAPI-Key: $RAPIDAPI_KEY" \
          -H "X-RapidAPI-Host: community-open-weather-map.p.rapidapi.com")

        echo "Weather API Response:"
        echo "$RESPONSE" | jq .  # Pretty print JSON

        # Optional: Save response to a file
        echo "$RESPONSE" > weather.json

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh

    - name: Add remote host to known_hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files via SCP
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: sshpass -e scp -r ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/website

    - name: Execute command on VPS
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: sshpass -e ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pm2 stop test-server && cd website && npm install && pm2 start test-server &"
