name: Fetch and Save Weather Data

on:
  push:
    branches:
      - main

jobs:
  weather_api_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y curl jq

    - name: List files
      run: ls -la

    - name: Fetch Meteostat API Data and Save to File
      env:
        METEOSTAT_API_KEY: ${{ secrets.METEOSTAT_API_KEY }}
      run: |
        API_URL="https://meteostat.p.rapidapi.com/point/monthly?lat=52.5244&lon=13.4105&alt=43&start=2020-01-01&end=2020-12-31"

        RESPONSE=$(curl -s --request GET "$API_URL" \
          --header "x-rapidapi-host: meteostat.p.rapidapi.com" \
          --header "x-rapidapi-key: $METEOSTAT_API_KEY")

        echo "$RESPONSE" | jq . > weather_data.txt  # Save formatted JSON to file

    - name: Show Generated File
      run: cat weather_data.txt  # Display the file content in GitHub Actions logs

    - name: Upload weather data as artifact
      uses: actions/upload-artifact@v4
      with:
        name: weather-data
        path: weather_data.txt
